### ISSUE TITLE
CantidadDeCartasInvalidaError ensucia los reports de ant

### ISSUE THREAD

**Issue by pabloernesto** [EzequielOrtega/Truco#2]
El constructor de CantidadDeCartasInvalidaError imprime el mesaje de error por stderr con cada nueva instancia. Esto puede ayudar al debugging, pero cuando no hay problemas aparece el error en los builds de ant.
Algunos test (testAgarrarCartasDevuelveErrorSiSeAgreganMasDeTres, y tal vez otros en el futuro) *esperan* la excepcion en situaciones normales; entonces **el mensaje de error va a aparecer** en el build report de ant **en situaciones normales.**

**Comment by pabloernesto** [comment]
Ditto con NoHayMasCartasError, PaloDeCartaInvalidoError, SoloSePuedeCantarEnPrimeraError, y ValorDeCartaInvalidoError.

**Comment by mcoul** [comment]
Hola Pablo, gracias por los warnings, pero ya tenemos un tutor de TP que se encarga de revisar el código y decirnos lo que hay que cambiar (Nico).
El test de mezclar cartas está comentado a propósito, porque tenía la duda de cuál es la mejor manera de testear que la máquina sepa (porque yo lo puedo averiguar imprimiendo un string de todas las cartas) que están mezcladas.
En cuanto a lo del mensaje de error, también lo hice yo, y por ahora me sirve, incluso cuando ant lo informa 'en condiciones normales', ya que me recuerda qué situaciones de error estoy testeando. Supongo que cuando esté terminado lo sacaré así queda prolijo.
Una lástima que no te hayan dejado unirte a algún grupo, pero al parecer por lo que escuché de Nico, parece que sos de los mejores TPs. Suerte con el 8!

**Comment by pabloernesto** [comment]
Muchas gracias por los buenos deseos! Voy a necesitar dosis iguales de suerte y trabajo duro, así que escucharte darme ánimos me pone de muy buen humor.

Les deseo la mejor de las suertes, y cuando quieran charlar ideas sobre el TP siéntanse libres de abrirme un issue :)  .
